<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkST0151ENSkillsNetwork20531532-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Data Visualization**

Estimated time needed: **30** minutes

In this lab, you will learn how to visualize and interpret data

## Objectives

*   Import Libraries
*   Lab Exercises
    *   Identifying duplicates
    *   Plotting Scatterplots
    *   Plotting Boxplots

***

## Import Libraries

All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.

In [1]:
import piplite
await piplite.install(['numpy'])
await piplite.install(['pandas'])
await piplite.install(['seaborn'])

Import the libraries we need for the lab

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

<ipython-input-2-2f07c4a88a8e>:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/teachingratings.csv'
resp = await fetch(URL)
ratings_url = io.BytesIO((await resp.arrayBuffer()).to_py())

Read in the csv file from the url using the request library

In [4]:
df = pd.read_csv(ratings_url)
df.head()

,minority,age,gender,credits,beauty,eval,division,native,tenure,students,allstudents,prof,PrimaryLast,vismin,female,single_credit,upper_division,English_speaker,tenured_prof
0,yes,36,female,more,0.289916,4.3,upper,yes,yes,24,43,1,0,1,1,0,1,1,1
1,yes,36,female,more,0.289916,3.7,upper,yes,yes,86,125,1,0,1,1,0,1,1,1
2,yes,36,female,more,0.289916,3.6,upper,yes,yes,76,125,1,0,1,1,0,1,1,1
3,yes,36,female,more,0.289916,4.4,upper,yes,yes,77,123,1,1,1,1,0,1,1,1
4,no,59,male,more,-0.737732,4.5,upper,yes,yes,17,20,2,0,0,0,0,1,1,1

In [5]:
df.shape

(463, 19)

In [6]:
df

,minority,age,gender,credits,beauty,eval,division,native,tenure,students,allstudents,prof,PrimaryLast,vismin,female,single_credit,upper_division,English_speaker,tenured_prof
0,yes,36,female,more,0.289916,4.3,upper,yes,yes,24,43,1,0,1,1,0,1,1,1
1,yes,36,female,more,0.289916,3.7,upper,yes,yes,86,125,1,0,1,1,0,1,1,1
2,yes,36,female,more,0.289916,3.6,upper,yes,yes,76,125,1,0,1,1,0,1,1,1
3,yes,36,female,more,0.289916,4.4,upper,yes,yes,77,123,1,1,1,1,0,1,1,1
4,no,59,male,more,-0.737732,4.5,upper,yes,yes,17,20,2,0,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,no,37,male,more,0.933396,3.5,upper,yes,yes,15,17,40,1,0,0,0,1,1,1
459,no,58,female,more,0.111563,3.5,upper,yes,yes,26,34,47,1,0,1,0,1,1,1
460,no,42,male,more,-0.900580,4.0,upper,yes,yes,45,86,61,1,0,0,0,1,1,1
461,no,39,male,more,0.643014,4.3,upper,yes,yes,22,29,62,1,0,0,0,1,1,1
462,no,51,female,more,0.391822,3.0,upper,yes,yes,47,67,69,1,0,1,0,1,1,1

## Lab Exercises

### Identify all duplicate cases using prof. Using all observations, find the average and standard deviation for age. Repeat the analysis by first filtering the data set to include one observation for each instructor with a total number of observations restricted to 94.

Identify all duplicate cases using prof variable - find the unique values of the prof variables

In [13]:
df[["prof"]]

     prof
0       1
1       1
2       1
3       1
4       2
..    ...
458    40
459    47
460    61
461    62
462    69

[463 rows x 1 columns]

In [7]:
df["prof"].unique

<bound method Series.unique of 0       1
1       1
2       1
3       1
4       2
       ..
458    40
459    47
460    61
461    62
462    69
Name: prof, Length: 463, dtype: int64>

Print out the number of unique values in the prof variable

In [11]:
df["prof"].nunique()

94

Using all observations, Find the average and standard deviation for age

In [15]:
df['age'].mean()

48.365010799136066

In [14]:
df['age'].std()

9.80274203786482

Repeat the analysis by first filtering the data set to include one observation for each instructor with a total number of observations restricted to 94.

> first we drop duplicates using prof as a subset and assign it a new dataframe name called no_duplicates_ratings_df

In [ ]:
no_duplicates_ratings_df = ratings_df.drop_duplicates(subset =['prof'])
no_duplicates_ratings_df.head()

> Use the new dataset to get the mean of age

In [ ]:
no_duplicates_ratings_df['age'].mean()

In [ ]:
no_duplicates_ratings_df['age'].std()

### Using a bar chart, demonstrate if instructors teaching lower-division courses receive higher average teaching evaluations.

In [ ]:
ratings_df.head()

Find the average teaching evaluation in both groups of upper and lower-division

In [ ]:
division_eval = ratings_df.groupby('division')[['eval']].mean().reset_index()

Plot the barplot using the seaborn library

In [ ]:
sns.set(style="whitegrid")
ax = sns.barplot(x="division", y="eval", data=division_eval)
plt.show()

### Plot the relationship between age and teaching evaluation scores.

Create a scatterplot with the scatterplot function in the seaborn library

In [ ]:
ax = sns.scatterplot(x='age', y='eval', data=ratings_df)
plt.show()

### Using gender-differentiated scatter plots, plot the relationship between age and teaching evaluation scores.

Create a scatterplot with the scatterplot function in the seaborn library this time add the <code>hue</code> argument

In [ ]:
ax = sns.scatterplot(x='age', y='eval', hue='gender',
                     data=ratings_df)
plt.show()

### Create a box plot for beauty scores differentiated by credits.

We use the <code>boxplot()</code> function from the seaborn library

In [ ]:
ax = sns.boxplot(x='credits', y='beauty', data=ratings_df)
plt.show()

### What is the number of courses taught by gender?

We use the <code>catplot()</code> function from the seaborn library

In [ ]:
sns.catplot(x='gender', kind='count', data=ratings_df)
plt.show()

### Create a group histogram of taught by gender and tenure

We will add the <code>hue = Tenure</code> argument

In [ ]:
sns.catplot(x='gender', hue = 'tenure', kind='count', data=ratings_df)
plt.show()

### Add division as another factor to the above histogram

We add another argument named <code>row</code> and use the division variable as the row

In [ ]:
sns.catplot(x='gender', hue = 'tenure', row = 'division',
            kind='count', data=ratings_df,
            height = 3, aspect = 2)
plt.show()

### Create a scatterplot of age and evaluation scores, differentiated by gender and tenure

Use the <code>relplot()</code> function for complex scatter plots

In [ ]:
sns.relplot(x="age", y="eval", hue="gender",
            row="tenure",
            data=ratings_df, height = 3, aspect = 2)
plt.show()

### Create a distribution plot of teaching evaluation scores

We use the <code>displot()</code> function from the seaborn library, set <code>kde = false</code> because we don'e need the curve

In [ ]:
ax = sns.displot(ratings_df['eval'], kde = False)
plt.show()

### Create a distribution plot of teaching evaluation score with gender as a factor

In [ ]:
## use the displot function from the seaborn library
sns.displot(ratings_df[ratings_df['gender'] == 'female']['eval'], color='green', kde=False) 
sns.displot(ratings_df[ratings_df['gender'] == 'male']['eval'], color="orange", kde=False) 
plt.show()

### Create a box plot - age of the instructor by gender

In [ ]:
ax = sns.boxplot(x="gender", y="age", data=ratings_df)
plt.show()

### Compare age along with tenure and gender

In [ ]:
ax = sns.boxplot(x="tenure", y="age", hue="gender",
                 data=ratings_df)
plt.show()

## Practice Questions

### Question 1: Create a distribution plot of beauty scores with Native English speaker as a factor

*   Make the color of the native English speakers plot - orange and non - native English speakers - blue

In [ ]:
## insert code

Double-click **here** for the solution.

<!-- The answer is below:
sns.displot(ratings_df[ratings_df['native'] == 'yes']['beauty'], color="orange", kde=False) 
sns.displot(ratings_df[ratings_df['native'] == 'no']['beauty'], color="blue", kde=False) 
plt.show()
-->

### Question 2: Create a Horizontal box plot of the age of the instructors by visible minority

In [ ]:
## insert code

Double-click **here** for a hint.

<!-- The hint is below:
Remember that the positions of the argument determine whether it will be vertical or horizontal
-->

Double-click **here** for the solution.

<!-- The answer is below:
ax = sns.boxplot(x="age", y="minority", data=ratings_df)
plt.show()
-->

### Question 3: Create a grouped bar plot of tenure by minority and add the gender factor

In [ ]:
## insert code

Double-click **here** for the solution.

<!-- The answer is below:
sns.catplot(x='tenure', hue = 'minority', row = 'gender',
            kind='count', data=ratings_df,
            height = 3, aspect = 2)
plt.show()
-->

### Question 4: Create a boxplot of the age variable

In [ ]:
## insert code

Double-click **here** for the solution.

<!-- The answer is below:
## you only habve to specify the y-variable
ax = sns.boxplot(y="age", data=ratings_df)
plt.show()
-->

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)
<!--
## Change Log

| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|
| 2024-09-27        | 1.1    | Anita Verma | Changed distplot to displot|
-->


<hr>

## <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>